### ISSUE TITLE
i.MX RT1064 FlexSPI configuration block

### ISSUE THREAD

**Issue by 90degs2infty** [imxrt-rs/imxrt-boot-gen#11]
Hi everybody!

I'm currently looking into the i.MX RT1064, trying to boot a `MIMXRT1064-EVK` using the `imxrt-rs` ecosystem. It works - at least to the extend that I am able to reproduce the basic example from [the book](https://imxrt-rs.github.io/book/ecosystem_walkthrough/hal.html) on said evk (the adapted example is available [here](https://github.com/90degs2infty/imxrt1064-rs-template)). Now that it works, I'm trying to understand how it works/what I actually did (I should have done it the other way round 😅 ).

Maybe you can shed some light on below questions on the generation of FlexSPI config blocks, please? I should start with a "disclaimer", though: I'm kind of new to both Rust and the embedded software development, so if you feel like my questions are out of place here, then that's fine, too.

Quick wrap-up of what I did: to the best of my knowledge, there is no "plug-and-play" fcb package targeting the 1064 like the ones shipped [e.g. for the 1010, 1060 and 1170](https://github.com/imxrt-rs/imxrt-boot-gen/tree/master/fcbs). To my understanding, the 1062 and the 1064 are quite similar, which is why I tried porting the fcb contained in the [`teensy4-rs` repository](https://github.com/mciantyre/teensy4-rs/tree/master/teensy4-fcb). Please find the result [here](https://github.com/90degs2infty/imxrt1064-fcb). Basically, there is only a single code change: [specify 4MB flash size instead of 2MB](https://github.com/90degs2infty/imxrt1064-fcb/blob/21c2394bc4dae9b05fc680d0df66c8acec1d7899/src/lib.rs#L120). Ah, and please correct me, if my understanding of this is wrong!

While reading through the code, I encountered several questions:

1. The opcodes, operands, pads and sequences have been taken from the mcus' reference manuals, right? I noticed a [corresponding comment in the sources](https://github.com/imxrt-rs/imxrt-boot-gen/blob/53281743919967d28db5434f3f31f98726f01e14/src/flexspi/sequence.rs#L3) Where does this docstring show up [in the docs](https://imxrt-rs.github.io/imxrt-boot-gen/imxrt_boot_gen/index.html)? I searched the docs for it, but I could not find it.
2. How did you choose which sequences to include in the code? In the reference manuals there are multiple sequences described  (IMXRT1060RM, rev. 3 and IMXRT1064RM, rev. 2; section 27.6.2 in both manuals), but not all of them are represented in code. Probably there just has to be one sequence per [`flexspi::Command`](https://imxrt-rs.github.io/imxrt-boot-gen/imxrt_boot_gen/flexspi/enum.Command.html), but then I guess the question simply becomes: how did you choose which commands to include in the code?
3. How did you decide in which order to place the sequences in a [lookup table](https://github.com/90degs2infty/imxrt1064-fcb/blob/21c2394bc4dae9b05fc680d0df66c8acec1d7899/src/lib.rs#L100)? I feel like I'm missing some part of documentation here.
4. Where did you take all the values required to setup the [common configuration block](https://github.com/90degs2infty/imxrt1064-fcb/blob/21c2394bc4dae9b05fc680d0df66c8acec1d7899/src/lib.rs#L112) from? Also, if you're aware of some material explaining the meaning of the individual values, please let me know 😃

Thank you so much for your help! 🙏

**Comment by teburd** [comment]
The configuration settings should come from the timning and requirements of the flash chip being used. E.g. some ISSI chip works up to X MHz, requires some delay between CS toggles, and wants read addresses written to a single SPI line, will return data in blocks of X using quad spi. The flash has blocks X bytes big that can be erased.

This information needs to then be translated into the table. For example if you were to modify the 1060evk for hyper flash boot (I'm tempted to try it) it would require a completely different configuration block.

Enabling the sdram so that its memory mapped would require... more configuration block updates.

And so on.

It's helpful to look at the FlexSPI IP docs, the flash chip docs, and imagine how you'd read/write to the flash chip with flexspi outside of the configuration block to understand this a little more I feel like. The block is sort of a template + metadata of what the boot rom needs to do just that.

**Comment by 90degs2infty** [comment]
Thanks for the clarification! I now get the overall idea of the configuration block.

To get into the details, I will certainly have to sort out the basic stuff first. It may sound silly, but not being familiar with the topic, I already struggle with:
> imagine how you'd read/write to the flash chip with flexspi outside of the configuration block to understand this a little more

In case you're familiar with some introductory material covering the general concepts, please let me know. If not, that's okay, too (i.e. no need to do the googleing on my behalf 😉 ).

**Comment by 90degs2infty** [comment]
Thanks for all the pointers! I'm currently looking into the materials (I had the reference manuals at hand before, but it certainly is a good idea to compare it so some code in the SDK or Zephyr). I guess for now it's best to close this issue. I will open more specific ones in case I encounter follow up questions.
